#!/bin/bash

CONFIG_FILE=$(cat $HOME/ACBOX/MCC_DAQ/config.json) 
DATA_DIR=$( echo "$CONFIG_FILE"  | jsawk 'return this.data_directory' )\
 && cp "$CONFIG_FILE" "${DATA_DIR}/SINGLE_config_$(date +"%s").json"

MODE="$(grep -Po '\"mode\":.*?[^\\]\",' config.json)"\
 && echo $MODE | grep "CONTINUOUS" > /dev/null \
  && source run_single_continuous.sh || source run_single_triggered.sh